from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi


uri = "mongodb+srv://MepDeveloper:dev_mep@maincluster.9tgxkix.mongodb.net/?retryWrites=true&w=majority"

# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("You successfully connected to MongoDB!")
except Exception as e:
    print(e)
    exit()

#get database
database = client.Mep_ML
#get collection
collection = database.StudentSubmissions
#create a object of json type
submission = {"student": "Manel",  "age": 20}
#insert in the database
#inserted_id returns _id autogenerated field
posted_id = collection.insert_one(submission).inserted_id
print(posted_id)
#getting the object
object = collection.find_one({"_id": posted_id})
print(object)

#refer to https://pymongo.readthedocs.io/en/stable/tutorial.html
#for more information