# Generated by Django 4.1.7 on 2023-04-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MepML", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="class",
            name="number_of_students",
        ),
        migrations.AddField(
            model_name="class",
            name="image",
            field=models.ImageField(blank=True, upload_to="Class_images/"),
        ),
    ]
