# Generated by Django 4.1.7 on 2023-05-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MepML", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="codesubmission",
            name="quantity_of_submissions",
            field=models.IntegerField(default=1),
        ),
    ]
