# Generated by Django 2.2.28 on 2023-03-31 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MepML', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='studenst',
            new_name='students',
        ),
    ]
