# Generated by Django 4.1.7 on 2023-04-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MepML", "0002_remove_class_number_of_students_class_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="students",
            field=models.ManyToManyField(blank=True, to="MepML.student"),
        ),
    ]
