# Generated by Django 2.2.28 on 2023-03-31 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MepML', '0002_auto_20230331_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asssignment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MepML.Professor'),
        ),
        migrations.AlterField(
            model_name='asssignment',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MepML.Dataset'),
        ),
        migrations.AlterField(
            model_name='class',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MepML.Professor'),
        ),
    ]
