# Generated by Django 4.1.7 on 2023-05-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MepML", "0003_alter_codesubmission_file_name_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="description",
            field=models.BinaryField(),
        ),
    ]
